### Site Settings ###
title               : Jinhyun Choi
description         : >-
                      Software Engineer: Graphics / Game
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : JinhyunChoi-DEV/JinhyunChoi-DEV.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Jinhyun Choi
  image             : assets/profile.jpg
  email             : choijinhyun.dev@gmail.com
  github            : JinhyunChoi-DEV
  instagram         : c_jinhyun_
  linkedin          : choijinhyun-dev
  spotify           : 31xng77xplz36l4crporwehdhpyq
  youtube           : channel/UCaBmVwuoW-PnSVEJ7pFr97A


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  soloprojects:
    output: true
    permalink: /soloprojects/:name

  teamprojects:
    output: true
    permalink: /teamprojects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
